name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build and Deploy
        run: |
          npm run build  # Build your project
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/yourusername/yourrepo.git" HEAD:gh-pages
        env:
          NODE_ENV: production
